### ISSUE TITLE
提两个需求

### ISSUE THREAD

**Issue by yaojunyi3721** [JayFang1993/DropDownMenu#6]
1.设置展开列表的列表项itemView的高度 目前的高度最多适合普通手机显示四五个列表项,再多比如10个列表项我就想缩小点高度以在当前页面显示更多的列表项而不用上下滚动
2.当ShowCount小于列表项数量导致需上下滚动时,设置是否一直显示纵向滚动条,以给app使用者明确的提示告知其展开的下拉框面板下面还有数据可选择

**Comment by JayFang1993** [comment]
@yaojunyi3721 对于需求1，还算比较常见，可以考虑，也欢迎提PR；对于需求2，我觉得没必要，而且任何地方带滚动的都是有交互的时候才会显示滚动条
