### ISSUE TITLE
在PopupWindow上加入这个控件不显示

### ISSUE THREAD

**Issue by cfr999** [JayFang1993/DropDownMenu#9]
View popupView = getLayoutInflater().inflate(R.layout.textview_change,
				null);
DropDownMenu mMenu_ziti = (DropDownMenu) popupView.findViewById(R.id.menu_ziti);

mPopupWindow = new PopupWindow(popupView, LayoutParams.WRAP_CONTENT,
				LayoutParams.WRAP_CONTENT, true);
		mPopupWindow.setFocusable(true);
		// mPopupWindow.setOutsideTouchable(false);
		mPopupWindow.setBackgroundDrawable(getDrawable(R.color.white));
		mPopupWindow.showAtLocation(rLayout, Gravity.CENTER, 0, 0);
最后运行结果看不到这个控件,在这个控件的外面包裹一个黑色背景的布局,可以看到这个布局,
没有报错,没有错误log.
我把代码分离出来,写了个Demo,结果可以显示没问题.
有谁知道为什么吗????????????

**Comment by JayFang1993** [comment]
你这个需求应该做不了~ DropDownMenu本身就是使用PopupWindow实现，这相当于在PopupWindow上弹PopupWindow，这个应该实现不了~
